# Generated by Django 3.2.12 on 2022-03-05 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uservalidation', '0002_hni_wm'),
    ]

    operations = [
        migrations.CreateModel(
            name='WMtoHNI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uservalidation.hni')),
                ('wm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uservalidation.wm')),
            ],
        ),
    ]
