# Generated by Django 3.2.12 on 2022-03-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uservalidation', '0003_wmtohni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('accepted', models.BooleanField(default=False)),
                ('hni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uservalidation.hni')),
                ('wm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uservalidation.wm')),
            ],
        ),
    ]
